### ISSUE TITLE
Alpine 2.6 - Can't compile Nokogiri 

### ISSUE THREAD

**Issue by thibpoullain** [docker-library/ruby#318]
Hi there :)

I created a very simple gitlab-ci.yml :

```
stages:
  - build
image: ruby:2.6-alpine
before_script:
  - gem install bundler --no-document
  - bundle install

build:rubocop:
  stage: build
  script:
    - bundle exec rubocop
  tags:
   - sdln
```

I've got an : 

```
Installing nokogiri 1.10.9 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
    current directory: /usr/local/bundle/gems/nokogiri-1.10.9/ext/nokogiri
/usr/local/bin/ruby -I /usr/local/lib/ruby/2.6.0 -r
./siteconf20200507-20-958m1i.rb extconf.rb
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.
```

I tried to add 

`  - apk add --no-cache gmp-dev` in my `before_script` but no success...

Have you got an idea ? I looked for an answer on google, seems that the solution was gmp-dev...

thx !
