### ISSUE TITLE
Install bundle gem in the same path as the system gems are

### ISSUE THREAD

**Issue by vovimayhem** [docker-library/ruby#53]
I'm having this use case in which I bring up several containers of the same ruby (rails) app with different commands using `docker-compose` for my development enviroment:

```yml
# Obviating some keys to keep the example lean:
web: &app
  image: ruby:2.2.3
  volumes:
    - .:/usr/src/app
  command: rails s -p 3000
jobs:
  <<: *app
  command: sidekiq -c 25 -q default
```

Using this image will require me to call `bundle install` on each container... but since is the same app, exactly the same gems will be installed on each container... I could mount a volume from a data-container on the `/usr/local/bundle` path, so both containers use the same installed gems:

```yml
gems:
  image: tianon/true
  volumes:
    - /usr/local/bundle
web: &app
  image: ruby:2.2.3
  volumes:
    - .:/usr/src/app
  volumes_from:
    - gems
  command: rails s -p 3000
jobs:
  <<: *app
  command: sidekiq -c 25 -q default
```

...but this will wipe out the image's installed bundler, as it's installed precisely on the `/usr/local/bundle` path.

How about installing bundler *BEFORE* setting the `$GEM_HOME` in this image's `Dockerfile`? Like this:

```
ENV BUNDLER_VERSION 1.10.6

# some of ruby's build scripts are written in ruby
# we purge this later to make sure our final image uses what we just built
RUN apt-get update \
	&& apt-get install -y bison libgdbm-dev ruby \
	&& rm -rf /var/lib/apt/lists/* \
	&& mkdir -p /usr/src/ruby \
	&& curl -fSL -o ruby.tar.gz "http://cache.ruby-lang.org/pub/ruby/$RUBY_MAJOR/ruby-$RUBY_VERSION.tar.gz" \
	&& echo "$RUBY_DOWNLOAD_SHA256 *ruby.tar.gz" | sha256sum -c - \
	&& tar -xzf ruby.tar.gz -C /usr/src/ruby --strip-components=1 \
	&& rm ruby.tar.gz \
	&& cd /usr/src/ruby \
	&& autoconf \
	&& ./configure --disable-install-doc \
	&& make -j"$(nproc)" \
	&& make install \
	&& apt-get purge -y --auto-remove bison libgdbm-dev ruby \
	&& gem update --system $RUBYGEMS_VERSION \
	&& rm -r /usr/src/ruby \
	&& gem install bundler --version "$BUNDLER_VERSION"

# install things globally, for great justice
ENV GEM_HOME /usr/local/bundle
ENV PATH $GEM_HOME/bin:$PATH

RUN  bundle config --global path "$GEM_HOME" \
	&& bundle config --global bin "$GEM_HOME/bin"
```

Any issues with that?

Also, does anybody has a better workflow / technique for development using this image & docker-compose?

**Comment by yosifkit** [comment]
That seems valid to me.

You could just have them both use a local `Dockerfile` with `build: .` in the compose yaml.
```Dockerfile
FROM ruby:2.2.3
ADD Gemfile* /usr/src/app/
RUN bundle install
ADD . /usr/src/app/
```
You'll just have to remember to rebuild when you make `Gemfile` changes.  Plus the Dockerfile can be used to create a container to deploy.

**Comment by vovimayhem** [comment]
That pretty much works, however I was aiming at a simpler workflow by sparing me from using `build .` on the docker-compose file.

What I ended using is the same ruby image to create a data-only container, something similar to this:

```yml
gems: &app_base
  image: ruby:2.2.3
  volumes: [ ".:/usr/src/app", "/usr/local/bundle" ]
  working_dir: /usr/src/app
jobs: &app
  <<: *app_base
  volumes_from: [ "gems" ]
  entrypoint: /usr/src/app/dev-entrypoint.sh
  command: sidekiq -c 25
jobs:
  <<: *app
  command: rails s -p 3000
  ports: [ "3000:3000" ]
```

The [entrypoint script](https://github.com/vovimayhem/rails-docker-demo/blob/master/dev-entrypoint.sh) runs the `bundle install` command, within a lock routine to prevent concurrent bundle installs.

It would still be nice if bundler was installed in the same place as the system gems in this official image, tho. Bundler seems to be pretty ubiquitous, and almost everyone expects to be part of a somewhat default install or ruby - I know it is not the case with the official installer, but take a hint at what RVM, Rbenv and ruby-install do.
